namespace KH2.ManagementSystem.Infrastructure.Persistence.Seed;

internal static class QuranSurahCatalog
{
    public static IReadOnlyList<QuranSurahSeedItem> All { get; } =
    [
        new(1, "Al-Fatihah", "الفاتحة", 7),
        new(2, "Al-Baqarah", "البقرة", 286),
        new(3, "Ali 'Imran", "آل عمران", 200),
        new(4, "An-Nisa", "النساء", 176),
        new(5, "Al-Ma'idah", "المائدة", 120),
        new(6, "Al-An'am", "الأنعام", 165),
        new(7, "Al-A'raf", "الأعراف", 206),
        new(8, "Al-Anfal", "الأنفال", 75),
        new(9, "At-Tawbah", "التوبة", 129),
        new(10, "Yunus", "يونس", 109),
        new(11, "Hud", "هود", 123),
        new(12, "Yusuf", "يوسف", 111),
        new(13, "Ar-Ra'd", "الرعد", 43),
        new(14, "Ibrahim", "إبراهيم", 52),
        new(15, "Al-Hijr", "الحجر", 99),
        new(16, "An-Nahl", "النحل", 128),
        new(17, "Al-Isra", "الإسراء", 111),
        new(18, "Al-Kahf", "الكهف", 110),
        new(19, "Maryam", "مريم", 98),
        new(20, "Taha", "طه", 135),
        new(21, "Al-Anbiya", "الأنبياء", 112),
        new(22, "Al-Hajj", "الحج", 78),
        new(23, "Al-Mu'minun", "المؤمنون", 118),
        new(24, "An-Nur", "النور", 64),
        new(25, "Al-Furqan", "الفرقان", 77),
        new(26, "Ash-Shu'ara", "الشعراء", 227),
        new(27, "An-Naml", "النمل", 93),
        new(28, "Al-Qasas", "القصص", 88),
        new(29, "Al-Ankabut", "العنكبوت", 69),
        new(30, "Ar-Rum", "الروم", 60),
        new(31, "Luqman", "لقمان", 34),
        new(32, "As-Sajdah", "السجدة", 30),
        new(33, "Al-Ahzab", "الأحزاب", 73),
        new(34, "Saba", "سبأ", 54),
        new(35, "Fatir", "فاطر", 45),
        new(36, "Ya-Sin", "يس", 83),
        new(37, "As-Saffat", "الصافات", 182),
        new(38, "Sad", "ص", 88),
        new(39, "Az-Zumar", "الزمر", 75),
        new(40, "Ghafir", "غافر", 85),
        new(41, "Fussilat", "فصلت", 54),
        new(42, "Ash-Shura", "الشورى", 53),
        new(43, "Az-Zukhruf", "الزخرف", 89),
        new(44, "Ad-Dukhan", "الدخان", 59),
        new(45, "Al-Jathiyah", "الجاثية", 37),
        new(46, "Al-Ahqaf", "الأحقاف", 35),
        new(47, "Muhammad", "محمد", 38),
        new(48, "Al-Fath", "الفتح", 29),
        new(49, "Al-Hujurat", "الحجرات", 18),
        new(50, "Qaf", "ق", 45),
        new(51, "Adh-Dhariyat", "الذاريات", 60),
        new(52, "At-Tur", "الطور", 49),
        new(53, "An-Najm", "النجم", 62),
        new(54, "Al-Qamar", "القمر", 55),
        new(55, "Ar-Rahman", "الرحمن", 78),
        new(56, "Al-Waqi'ah", "الواقعة", 96),
        new(57, "Al-Hadid", "الحديد", 29),
        new(58, "Al-Mujadilah", "المجادلة", 22),
        new(59, "Al-Hashr", "الحشر", 24),
        new(60, "Al-Mumtahanah", "الممتحنة", 13),
        new(61, "As-Saff", "الصف", 14),
        new(62, "Al-Jumu'ah", "الجمعة", 11),
        new(63, "Al-Munafiqun", "المنافقون", 11),
        new(64, "At-Taghabun", "التغابن", 18),
        new(65, "At-Talaq", "الطلاق", 12),
        new(66, "At-Tahrim", "التحريم", 12),
        new(67, "Al-Mulk", "الملك", 30),
        new(68, "Al-Qalam", "القلم", 52),
        new(69, "Al-Haqqah", "الحاقة", 52),
        new(70, "Al-Ma'arij", "المعارج", 44),
        new(71, "Nuh", "نوح", 28),
        new(72, "Al-Jinn", "الجن", 28),
        new(73, "Al-Muzzammil", "المزمل", 20),
        new(74, "Al-Muddaththir", "المدثر", 56),
        new(75, "Al-Qiyamah", "القيامة", 40),
        new(76, "Al-Insan", "الإنسان", 31),
        new(77, "Al-Mursalat", "المرسلات", 50),
        new(78, "An-Naba", "النبأ", 40),
        new(79, "An-Nazi'at", "النازعات", 46),
        new(80, "Abasa", "عبس", 42),
        new(81, "At-Takwir", "التكوير", 29),
        new(82, "Al-Infitar", "الانفطار", 19),
        new(83, "Al-Mutaffifin", "المطففين", 36),
        new(84, "Al-Inshiqaq", "الانشقاق", 25),
        new(85, "Al-Buruj", "البروج", 22),
        new(86, "At-Tariq", "الطارق", 17),
        new(87, "Al-A'la", "الأعلى", 19),
        new(88, "Al-Ghashiyah", "الغاشية", 26),
        new(89, "Al-Fajr", "الفجر", 30),
        new(90, "Al-Balad", "البلد", 20),
        new(91, "Ash-Shams", "الشمس", 15),
        new(92, "Al-Layl", "الليل", 21),
        new(93, "Ad-Duha", "الضحى", 11),
        new(94, "Ash-Sharh", "الشرح", 8),
        new(95, "At-Tin", "التين", 8),
        new(96, "Al-Alaq", "العلق", 19),
        new(97, "Al-Qadr", "القدر", 5),
        new(98, "Al-Bayyinah", "البينة", 8),
        new(99, "Az-Zalzalah", "الزلزلة", 8),
        new(100, "Al-Adiyat", "العاديات", 11),
        new(101, "Al-Qari'ah", "القارعة", 11),
        new(102, "At-Takathur", "التكاثر", 8),
        new(103, "Al-Asr", "العصر", 3),
        new(104, "Al-Humazah", "الهمزة", 9),
        new(105, "Al-Fil", "الفيل", 5),
        new(106, "Quraysh", "قريش", 4),
        new(107, "Al-Ma'un", "الماعون", 7),
        new(108, "Al-Kawthar", "الكوثر", 3),
        new(109, "Al-Kafirun", "الكافرون", 6),
        new(110, "An-Nasr", "النصر", 3),
        new(111, "Al-Masad", "المسد", 5),
        new(112, "Al-Ikhlas", "الإخلاص", 4),
        new(113, "Al-Falaq", "الفلق", 5),
        new(114, "An-Nas", "الناس", 6)
    ];
}

internal sealed record QuranSurahSeedItem(
    int Number,
    string Name,
    string ArabicName,
    int VerseCount);
