// <auto-generated />
using System;
using KH2.ManagementSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace KH2.ManagementSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Auth.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Email");

                    b.ToTable("EmailVerificationCodes", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.AttendanceDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AttendanceDevices", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceAttendanceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kegiatan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("KegiatanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kelas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OpenerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SesiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Waktu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("KegiatanId");

                    b.HasIndex("OpenerUserId");

                    b.HasIndex("SesiId");

                    b.HasIndex("Tanggal", "Status");

                    b.ToTable("FaceAttendanceSessions", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CaptureIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(512)");

                    b.Property<Guid>("FaceEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<float?>("QualityScore")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FaceEnrollmentId");

                    b.ToTable("FaceEmbeddings", null, t =>
                        {
                            t.HasCheckConstraint("CK_FaceEmbeddings_CaptureIndex_Positive", "\"CaptureIndex\" > 0");

                            t.HasCheckConstraint("CK_FaceEmbeddings_QualityScore_Range", "\"QualityScore\" IS NULL OR (\"QualityScore\" >= 0 AND \"QualityScore\" <= 1)");
                        });
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptedSampleCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FaceProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FaceProfileId");

                    b.HasIndex("FaceProfileId", "Status")
                        .IsUnique()
                        .HasDatabaseName("UX_FaceEnrollments_Active_FaceProfile")
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("FaceEnrollments", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceEnrollmentCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Pose")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId", "Sequence")
                        .IsUnique();

                    b.ToTable("FaceEnrollmentCaptures", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SantriId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentEnrollmentId");

                    b.HasIndex("SantriId")
                        .IsUnique();

                    b.ToTable("FaceProfiles", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceRecognitionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("FaceEnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FaceProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PresensiId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProcessingDurationMs")
                        .HasColumnType("integer");

                    b.Property<bool>("Recognized")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SantriId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SesiId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Similarity")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FaceEnrollmentId");

                    b.HasIndex("FaceProfileId");

                    b.HasIndex("PresensiId");

                    b.HasIndex("SantriId");

                    b.HasIndex("DeviceId", "CreatedAtUtc");

                    b.HasIndex("SesiId", "SantriId");

                    b.ToTable("FaceRecognitionEvents", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.LegacyFaceEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CaptureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EmbeddingUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LegacyFaceEnrollments", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.LegacyFaceEnrollmentCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Pose")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId", "Sequence")
                        .IsUnique();

                    b.ToTable("LegacyFaceEnrollmentCaptures", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.LegacyFaceRecognitionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PresensiId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("SantriId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PresensiId");

                    b.HasIndex("SantriId");

                    b.HasIndex("SessionId", "CapturedAtUtc");

                    b.ToTable("LegacyFaceRecognitionEvents", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.ProviderFaceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EmbeddingUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderProfileId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProfileId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProviderFaceProfiles", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.JurnalKeilmuans.JurnalKeilmuan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("AdaMateri")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DibuatOleh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DibuatOlehUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("JamMengajar")
                        .HasColumnType("numeric");

                    b.Property<string>("JenisMateri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kelas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NamaDewanGuru")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("QuranAyatAwal")
                        .HasColumnType("integer");

                    b.Property<int?>("QuranAyatRealisasi")
                        .HasColumnType("integer");

                    b.Property<int?>("QuranAyatTarget")
                        .HasColumnType("integer");

                    b.Property<string>("QuranKeterangan")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("QuranRealisasiSurahId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuranTargetSurahId")
                        .HasColumnType("uuid");

                    b.Property<string>("SesiSambung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuranRealisasiSurahId");

                    b.HasIndex("QuranTargetSurahId");

                    b.HasIndex("Tanggal");

                    b.HasIndex("Tanggal", "JenisMateri");

                    b.ToTable("JurnalKeilmuans", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Kafarahs.Kafarah", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JenisPelanggaran")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("JumlahSetor")
                        .HasColumnType("integer");

                    b.Property<string>("KafarahText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Kafarah");

                    b.Property<Guid>("SantriId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.Property<int>("Tanggungan")
                        .HasColumnType("integer");

                    b.Property<string>("Tenggat")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SantriId", "Tanggal");

                    b.ToTable("Kafarahs", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Kegiatans.Kegiatan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Catatan")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Waktu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Kategori", "Waktu")
                        .IsUnique();

                    b.ToTable("Kegiatans", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.LogKeluarMasuks.LogKeluarMasuk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Catatan")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Petugas")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rentang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SantriId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("TanggalPengajuan")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TanggalPengajuan");

                    b.HasIndex("SantriId", "TanggalPengajuan");

                    b.ToTable("LogKeluarMasuks", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Presensis.Presensi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Catatan")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FaceAttendanceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KegiatanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SantriId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SesiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Waktu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Presensis_CreatedAtUtc_LegacyNullSesi")
                        .HasFilter("\"SesiId\" IS NULL");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("FaceAttendanceSessionId", "SantriId")
                        .IsUnique()
                        .HasDatabaseName("UX_Presensis_FaceAttendanceSessionId_SantriId")
                        .HasFilter("\"FaceAttendanceSessionId\" IS NOT NULL");

                    b.HasIndex("KegiatanId", "Waktu");

                    b.HasIndex("SantriId", "CreatedAtUtc");

                    b.HasIndex("SantriId", "Status");

                    b.HasIndex("SesiId", "CreatedAtUtc");

                    b.HasIndex("SesiId", "SantriId")
                        .IsUnique()
                        .HasDatabaseName("UX_Presensis_SesiId_SantriId")
                        .HasFilter("\"SesiId\" IS NOT NULL");

                    b.ToTable("Presensis", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.ProgressKeilmuans.ProgressKeilmuan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capaian")
                        .HasColumnType("integer");

                    b.Property<string>("Catatan")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pembimbing")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SantriId")
                        .HasColumnType("uuid");

                    b.Property<string>("Satuan")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TerakhirSetorUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("Level", "SantriId");

                    b.HasIndex("SantriId", "Judul");

                    b.HasIndex("SantriId", "UpdatedAtUtc");

                    b.ToTable("ProgressKeilmuans", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Quran.QuranSurah", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerseCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("QuranSurahs", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Santris.Santri", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Catatan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Jurusan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Kampus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kelas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Nis")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Santris", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Sesis.Sesi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Catatan")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KegiatanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KegiatanId");

                    b.HasIndex("Tanggal");

                    b.ToTable("Sesis", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Walis.WaliSantriRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelationshipLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SantriId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaliSantriCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WaliUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SantriId");

                    b.HasIndex("WaliSantriCode")
                        .IsUnique();

                    b.HasIndex("WaliUserId", "SantriId")
                        .IsUnique();

                    b.ToTable("WaliSantriRelations", (string)null);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceAttendanceSession", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Kegiatans.Kegiatan", null)
                        .WithMany()
                        .HasForeignKey("KegiatanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KH2.ManagementSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OpenerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KH2.ManagementSystem.Domain.Sesis.Sesi", null)
                        .WithMany()
                        .HasForeignKey("SesiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceEmbedding", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.FaceEnrollment", null)
                        .WithMany()
                        .HasForeignKey("FaceEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceEnrollment", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.FaceProfile", null)
                        .WithMany()
                        .HasForeignKey("FaceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceEnrollmentCapture", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.FaceEnrollment", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceProfile", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.FaceEnrollment", null)
                        .WithMany()
                        .HasForeignKey("CurrentEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KH2.ManagementSystem.Domain.Santris.Santri", null)
                        .WithOne()
                        .HasForeignKey("KH2.ManagementSystem.Domain.FaceRecognition.FaceProfile", "SantriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.FaceRecognitionEvent", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.AttendanceDevice", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.FaceEnrollment", null)
                        .WithMany()
                        .HasForeignKey("FaceEnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.FaceProfile", null)
                        .WithMany()
                        .HasForeignKey("FaceProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KH2.ManagementSystem.Domain.Presensis.Presensi", null)
                        .WithMany()
                        .HasForeignKey("PresensiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KH2.ManagementSystem.Domain.Santris.Santri", null)
                        .WithMany()
                        .HasForeignKey("SantriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KH2.ManagementSystem.Domain.Sesis.Sesi", null)
                        .WithMany()
                        .HasForeignKey("SesiId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.LegacyFaceEnrollment", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.LegacyFaceEnrollmentCapture", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.LegacyFaceEnrollment", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.LegacyFaceRecognitionEvent", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Presensis.Presensi", null)
                        .WithMany()
                        .HasForeignKey("PresensiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KH2.ManagementSystem.Domain.Santris.Santri", null)
                        .WithMany()
                        .HasForeignKey("SantriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.FaceAttendanceSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.FaceRecognition.ProviderFaceProfile", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.JurnalKeilmuans.JurnalKeilmuan", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Quran.QuranSurah", null)
                        .WithMany()
                        .HasForeignKey("QuranRealisasiSurahId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KH2.ManagementSystem.Domain.Quran.QuranSurah", null)
                        .WithMany()
                        .HasForeignKey("QuranTargetSurahId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Kafarahs.Kafarah", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Santris.Santri", null)
                        .WithMany()
                        .HasForeignKey("SantriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.LogKeluarMasuks.LogKeluarMasuk", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Santris.Santri", null)
                        .WithMany()
                        .HasForeignKey("SantriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Presensis.Presensi", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.FaceRecognition.FaceAttendanceSession", null)
                        .WithMany()
                        .HasForeignKey("FaceAttendanceSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KH2.ManagementSystem.Domain.Kegiatans.Kegiatan", null)
                        .WithMany()
                        .HasForeignKey("KegiatanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KH2.ManagementSystem.Domain.Santris.Santri", null)
                        .WithMany()
                        .HasForeignKey("SantriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KH2.ManagementSystem.Domain.Sesis.Sesi", null)
                        .WithMany()
                        .HasForeignKey("SesiId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.ProgressKeilmuans.ProgressKeilmuan", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Santris.Santri", null)
                        .WithMany()
                        .HasForeignKey("SantriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Santris.Santri", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("KH2.ManagementSystem.Domain.Santris.Santri", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Sesis.Sesi", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Kegiatans.Kegiatan", null)
                        .WithMany()
                        .HasForeignKey("KegiatanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KH2.ManagementSystem.Domain.Walis.WaliSantriRelation", b =>
                {
                    b.HasOne("KH2.ManagementSystem.Domain.Santris.Santri", null)
                        .WithMany()
                        .HasForeignKey("SantriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KH2.ManagementSystem.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("WaliUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
